app/urls.py
from django.urls import path

from . import views

app_name = 'app'
urlpatterns = [
    path('rayout',views.rayout,name='rayout'),
    path('',  views.index, name='index'),
    path('item/<slug:slug>', views.detail, name='detail'),
    path('form', views.form, name='form'),
    path('delete', views.delete, name='delete'),
    path('reload',views.reload, name='reload'),
    path('item/<slug:slug>/edit', views.edit,name='edit'),
    path('item/<slug:slug>/exclusion', views.exclusion, name='exclusion'),
    path('maker_index',views.maker_index, name='maker_index'),
    path('maker/<slug:slug>', views.maker_detail, name='maker_detail'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', admin.site.urls),
]

home/urls.py
from django.urls import path

from . import views

app_name = 'home'
urlpatterns = [
    # path('rayout',views.rayout,name='rayout'),
    path('',  views.index, name='index'),
    path('category',views.category, name='category'),
    path('contact', views.contact, name='contact'), 
    path('contact/done', views.done, name='done'),
    path('preturn', views.preturn, name='preturn'),
]

home/models.py
from django.db import models

class Item_category(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(null=False, unique=True)
    url = models.URLField(max_length=255)

    def __str__(self):
        return self.name
    

home/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.db.models import Q
from .forms import ContactForm
from .models import Item_category

from django.http import HttpResponse
from django.conf import settings
import textwrap
from django.core.mail import BadHeaderError, EmailMessage

def index(request):
    return render(request, 'home/index.html')

def category(request):
    categories = Item_category.objects.all()
    query = request.GET.get('query')
    if query:
        categories = categories.filter(
            Q(name__icontains=query)
        ).distinct()
    return render(request, 'home/category-list.html', {
        'categories':categories,
    })

def preturn(request):
    return render(request, 'home/preturn.html')

def contact(request):
  form = ContactForm(request.POST or None)
  if form.is_valid():
     name = form.cleaned_data['name']
     message = form.cleaned_data['message']
     email = form.cleaned_data['email']
     subject = 'お問い合わせありがとうございます。'
     contact = textwrap.dedent('''
        ※このメールはシステムからの自動返信です。

        {name} 様
        
        お問い合わせありがとうございます。
        以下の内容でお問い合わせを受け付けました。
        内容を確認させていただき、ご返信させていただきますので、少々お待ちください。

        ----------------------------------

        ・お名前
        {name}

        ・メールアドレス
        {email}

        ・メッセージ
        {message}
        
        -----------------------------------
        WEB: https://wanto-item.com/
     ''').format(
        name=name,
        email=email,
        message=message
     )
     to_list = [email]
     bcc_list = [settings.EMAIL_HOST_USER]
     try:
        message = EmailMessage(subject=subject, body=contact, to=to_list, bcc=bcc_list)
        message.send()
     except BadHeaderError:
        return HttpResponse('無効なヘッダが検出されました。')
     return redirect('home:done')

  return render(request, 'home/contact.html',{'form': form})

def done(request):
   return render(request, 'home/done.html')

home/templates/home/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <link rel='stylesheet' href="{% static 'home/css/style_base.css' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'home/icon/favicon_package/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'home/icon/favicon_package/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'home/icon/favicon_package/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'home/icon/favicon_package/site.webmanifest' %}">
    <link rel="mask-icon" href="{% static 'home/icon/favicon_package/safari-pinned-tab.svg' %}" color="#aeaeae">
    <meta name="msapplication-TileColor" content="#b8b8b8">
    <meta name="theme-color" content="#ffffff">
    <!-- <link rel="icon" href="{% static 'home/icon/favicon.ico' %}"> -->
    <script src="https://kit.fontawesome.com/81e08fdf06.js" crossorigin="anonymous"></script>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@400;700&family=Open+Sans:wght@400;700&display=swap" rel="stylesheet">
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-TM2RNP3WQR"></script>
    <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'G-TM2RNP3WQR');
    </script>
    {% block head %}
    {% endblock %}
</head>
<body>
    <header class="header">
        <div class="container">
            <div class="logo_header"><a href="{% url 'home:index' %}">WaNTo</a></div>
            <div class="maker_header"><a href="{% url 'home:category' %}">カテゴリ</a></div>
            <form class="form_header" action="{% url 'home:category' %}" method="GET">
                    <input name="query" value="{{ request.GET.query }}" type="text" id="sbox" placeholder="検索"/>
                    <button type="submit" id="sbtn"><i class="fas fa-search"></i></button>
            </form>

        </div>
    </header>
    {% block content %}
    {% endblock %}
    <footer>
        <div class="container">
            <a href="{% url 'home:contact' %}" class="contact">CONTACT</a>    
            <a href="{% url 'home:preturn' %}" class="question">FAQ</a>
        </div>
    </footer>
</body>
</html>

home/templates/home/category-list.html
{% extends 'home/base.html' %}
{% load static %}
{% block head %}
<link rel='stylesheet' href="{% static 'home/css/style_list.css' %}">
<title>カテゴリ一覧 - WaNTo(ワント)</title>
<meta name="description" content="アイテムのレビューや評価サイトだけを表示したいというお悩みはありませんか？本サイトでは、アイテムのレビューや評価サイトサイトだけを一覧表示！あなたに最適なアイテムを見つけてください。">
{% endblock %}
{% block content %}
<main>
    {% if categories %}
    {% for category in categories %}
    <div class="item_title">
        <div class="title_card"><a href="{{ category.url }}" target="_blank">{{ category.name }}</a></div>
    </div>
    {% endfor %}
    {% endif %}
</main>
{% endblock %}

home/templates/home/contact.html
{% extends 'home/base.html' %}
{% load static %}
{% block head %}
<link rel='stylesheet' href="{% static 'home/css/style_contact.css' %}">
{% endblock %}
{% block content %}
<main>
    <h1>お問い合わせ</h1>
    <form action="{% url 'home:contact' %}" method="POST" class="contact">
        {% csrf_token %}
        <input name="name" type="text" class="feedback-input" required="" placeholder="Name">   
        <input name="email" type="text" class="feedback-input" required="" placeholder="Email">
        <textarea name="message" class="feedback-input" required="" placeholder="Comment"></textarea>
        <input type="submit" value="SUBMIT">
    </form>
</main>
{% endblock %}

home/templates/home/done.html
{% extends 'home/base.html' %}
{% block content %}
<main>
    <h4 class="card-title">お問い合わせありがとうございます。</h4>
    <hr>
    <a href="{% url 'home:index' %}"><button type="button" class="btn btn-primary">トップページへ</button></a>
</main>
{% endblock%}

home/templates/home/index.html
{% extends 'home/base.html' %}
{% load static %}
{% block head %}
<link rel='stylesheet' href="{% static 'home/css/style_index.css' %}">
<title>WaNTo(ワント) - トップページ</title>
<meta name="description" content="アイテムのレビューや評価サイトだけを表示したいというお悩みはありませんか？本サイトでは、アイテムのレビューや評価サイトサイトだけを一覧表示！あなたに最適なアイテムを見つけてください。">
{% endblock %}
{% block content %}
<main>
    <div class="main_pic">
        <img src="{% static 'home/img/main_sp_pic.jpg' %}" class="sp">
        <img src="{% static 'home/img/main_pc_pic.jpg' %}" class="pc">
        <p class="main_title">WaNTo</p>
        <p class="in_title"><span class="under_line">シンプル</span>かつ<span class="under_line">ベスト</span></p>
        <p class="sub_title">みんなのレビューから<br>あなたに最適なアイテムを</p>
    </div>
    <div class="intro_grid">
        <div>
        <div class="line_1"></div>
        <p class="large_1"><span class="under_line">欲しいものを調べるとき、<br>
            このようなお悩みはありませんか？</span></p>
        <p class="normal_1">・実際に使っている人の感想を知りたい。<br>
            ・ショッピングサイトばかり表示してしまう。<br>
            ・ブログや商品紹介をしているページだけ見たい。
        </p>
        <div class="line_2"></div>
        <p class="arrow">⬇</p>
        <div class="line_3"></div>
        <p class="large_2"><span class="under_line">このサイトでは、</span></p>
        <p class="normal_2">①論理式を用いた検索（詳しくは<a href="{%  url 'home:preturn' %}">こちら</a>）<br>
            ②特定のショッピングサイトのurlをフィルター<br>
            ③特定のキーワード（通販や中古など）を含むタイトルのurlをフィルター
        </p>
        <img src="{% static 'home/img/sub_sp_pic.png' %}" class="sp">
        <img src="{% static 'home/img/sub_pc_pic.png' %}" class="pc">
        <div class="line_4"></div>
        <p class="large_3"><span class="under_line">本当に知りたい情報だけを取得！</span></p>
        <p class="large_4">カテゴリ一覧は<a href="{%  url 'home:category' %}">こちら</a>から</p>
        <p class="normal_3"> ＊カテゴリは随時更新中<br> ＊リクエストがあれば<a href="{%  url 'home:contact' %}">こちら</a>から</p>
        </div>
    </div>
</main>
{% endblock %}
 

home/templates/home/preturn.html
{% extends 'home/base.html' %}
{% load static %}
{% block content %}
<main>
<h1>準備中</h1>
<a href="{% url 'home:index' %}"><button type="button" class="btn btn-primary">トップページへ</button></a>
</main>
{% endblock %}

home/templates/home/rayout_detail.html
{% extends 'home/base.html' %}
{% load static %}
{% block head %}
    <link rel='stylesheet' href="{% static 'home/css/style_detail.css' %}">
{% endblock %}
{% block content %}
<main>
    <div class="item_title">
        <div class="title_card">メーカー</div>
        <div class="title_card">アイテム</div>
        <div class="item_article_card">
            <a>
                <div>タイトルタイトルタイトルタイトルタイトルタイトルタイトルタイトルタイトルタイトルタイトルタイトルタイトルタイトルタイトルタイトルタイトルタイトルタイトル</div>
                <img src="https://pc.watch.impress.co.jp/img/pcw/list/1290/745/H00.jpg">
            </a>
            <a>
                <div>URL2</div>
                <img src="https://pc.watch.impress.co.jp/img/pcw/list/1290/745/H00.jpg">
            </a>
            <a>
                <div>URL3</div>
                <img src="https://pc.watch.impress.co.jp/img/pcw/list/1290/745/H00.jpg">
            </a>

            <!-- <div>URL4</div> --> -->
        </div>
    </div>
    <!-- <div class="item_title">
        <div class="title_card">メーカー</div>
        <div class="title_card">アイテム</div>
        <div class="item_article_card">
            <div><img src="https://pc.watch.impress.co.jp/img/pcw/list/1290/745/H00.jpg">URL1</div>
            <div>URL2</div>
            <div>URL3</div>
            <div>URL4</div>
        </div>
    </div> -->
</main>
{% endblock %}

home/templates/home/rayout_index.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <link rel='stylesheet' href="{% static 'home/css/style_base.css' %}">
    <link rel='stylesheet' href="{% static 'home/css/style_index.css' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'home/icon/favicon_package/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'home/icon/favicon_package/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'home/icon/favicon_package/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'home/icon/favicon_package/site.webmanifest' %}">
    <link rel="mask-icon" href="{% static 'home/icon/favicon_package/safari-pinned-tab.svg' %}" color="#aeaeae">
    <meta name="msapplication-TileColor" content="#b8b8b8">
    <meta name="theme-color" content="#ffffff">
    <!-- <link rel="icon" href="{% static 'home/icon/favicon.ico' %}"> -->
    <script src="https://kit.fontawesome.com/81e08fdf06.js" crossorigin="anonymous"></script>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@400;700&family=Open+Sans:wght@400;700&display=swap" rel="stylesheet">
    <title>WaNTo</title>
</head>

<body>
    <header class="header">
        <div class="container">
            <div class="logo_header"><a href="{% url 'home:index' %}">WaNTo</a></div>
            <div class="maker_header"><a href="{% url 'home:maker_index' %}">メーカー</a></div>
            <form class="form_header" action="{% url 'home:index' %}" method="GET">
                    <input name="query" value="{{ request.GET.query }}" type="text" id="sbox" placeholder="検索"/>
                    <button type="submit" id="sbtn"><i class="fas fa-search"></i></button>
            </form>

        </div>
    </header>
    <main>
        <div class="item_title">
            <div class="title_card">メーカー1</div>
            <div class="item_card">
                <div class="item"><a>アイテム1アイテム1アイテム1アイテム1アイテム1</a></div>
                <div class="item">アイテム2</div>
                <div class="item">アイテム3</div>
                <div class="item">アイテム4</div>
            </div>
        </div>
        <div class="item_title">
            <div class="title_card">メーカー2</div>
            <div class="item_card">
                <div class="item">アイテム5</div>
                <div class="item">アイテム6</div>
                <div class="item">アイテム7</div>
                <div class="item">アイテム8</div>
                <div class="item">アイテム9</div>
            </div>
        </div>
    </main>
    <footer>
        <div class="container">
            <a class="contact">お問い合わせ</a>    
            <a class="question">FAQ</a>
        </div>
    </footer>
</body>

</html>