app/urls.py
from django.urls import path

from . import views

app_name = 'app'
urlpatterns = [
    path('rayout',views.rayout,name='rayout'),
    path('',  views.index, name='index'),
    path('item/<slug:slug>', views.detail, name='detail'),
    path('form', views.form, name='form'),
    path('delete', views.delete, name='delete'),
    path('reload',views.reload, name='reload'),
    path('item/<slug:slug>/edit', views.edit,name='edit'),
    path('item/<slug:slug>/exclusion', views.exclusion, name='exclusion'),
    path('maker_index',views.maker_index, name='maker_index'),
    path('maker/<slug:slug>', views.maker_detail, name='maker_detail'),
]

ca_lens/urls.py
from django.urls import path

from . import views

app_name = 'ca_lens'
urlpatterns = [
    path('',  views.index, name='index'),
    path('item/<slug:slug>', views.detail, name='detail'),
    path('delete', views.delete, name='delete'),
    path('item/<slug:slug>/exclusion', views.exclusion, name='exclusion'),
    path('maker_index',views.maker_index, name='maker_index'),
    path('maker/<slug:slug>', views.maker_detail, name='maker_detail'),
    path('contact', views.contact, name='contact'), 
    path('contact/done', views.done, name='done'),
    path('search_result', views.search_result, name='search_result'),
    path('preturn', views.preturn, name="preturn"),
    # path('rayout',views.rayout,name='rayout'),
    # path('form', views.form, name='form'),
    # path('reload/',views.reload, name='reload'),
    # path('item/<slug:slug>/edit', views.edit,name='edit'),
    # path('item/<slug:slug>/reload_one', views.reload_one, name='reload_one'),
    # path('celery_test/', views.celery_test, name='celery_test'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', admin.site.urls),
]

ca_lens/models.py
from django.db import models
from adminsortable.models import SortableMixin
from adminsortable.fields import SortableForeignKey

from . import def_chrome 

class Item_maker(SortableMixin):
    name = models.CharField(max_length=255)
    slug = models.SlugField(null=False, unique=True)
    meta_des = models.CharField(max_length=255,default='<meta name="description" content="カメラのレビューや評価サイトだけを表示したいというお悩みはありませんか？本サイトでは、カメラのレビューや評価サイトサイトだけを一覧表示！あなたに最適なアイテムを見つけてください。">')
    the_order = models.PositiveIntegerField(default=0, editable=False, db_index=True)

    class Meta:
        ordering = ["the_order"]

    def __str__(self):
        return self.name
    
class Tag(models.Model):
    name = models.CharField(max_length=255)
    
    def __str__(self):
        return self.name
    
class Wantoitem(SortableMixin):
    item_name = models.CharField(blank=True,null=True,max_length=255)
    maker_name = SortableForeignKey(Item_maker,on_delete=models.PROTECT)
    tag = models.ManyToManyField(Tag, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    slug = models.SlugField(null=False, unique=True)
    meta_des = models.CharField(max_length=255,default='<meta name="description" content="カメラのレビューや評価サイトだけを表示したいというお悩みはありませんか？本サイトでは、カメラのレビューや評価サイトサイトだけを一覧表示！あなたに最適なアイテムを見つけてください。">')
    the_order = models.PositiveIntegerField(default=0, editable=False, db_index=True)

    class Meta:
        ordering = ["the_order"]
            
    def __str__(self):
        return self.item_name

    def scraping(self):
        driver = def_chrome.make_driver()
        # print('途中１-ドライバ初期設定')
        driver.get("https://google.com")
        kw_in_title_path = '/workspace/ca_lens/pattern/kw_in_title.txt'
        kw_out_title_path = '/workspace/ca_lens/pattern/kw_out_title.txt'
        kw_in_list = def_chrome.kw_in_title(kw_in_title_path)
        kw_out_list = def_chrome.kw_out_title(kw_out_title_path)
        search_word = self.maker_name.name+' AND '+self.item_name+' AND '+('({0})'+' -{1}').format(kw_in_list,kw_out_list)
        # print('途中１-検索ワード')
        def_chrome.search(driver, search_word)
        # print('途中１-ドライバー起動')
        except_file_main = '/workspace/ca_lens/pattern/except_main_list.txt'
        except_file_sub = '/workspace/ca_lens/pattern/except_sub_list.txt'
        contain_title = '/workspace/ca_lens/pattern/contain_title.txt'
        except_title = '/workspace/ca_lens/pattern/except_title.txt'

        in_keyword,out_keyword = def_chrome.get_url(driver,except_file_main,except_file_sub,contain_title,except_title)
        driver.close()
        return in_keyword,out_keyword

class Main(models.Model):
    wantoitem = models.ForeignKey(Wantoitem, on_delete=models.CASCADE) 
    main_url = models.URLField(max_length=200)
    main_title = models.CharField(max_length=255)
    main_ogp_img = models.URLField(max_length =200,blank=True,null=True)

class Sub(models.Model):
    wantoitem = models.ForeignKey(Wantoitem, on_delete=models.CASCADE)
    sub_url = models.URLField(max_length =200)
    sub_title = models.CharField(max_length=255)
    sub_ogp_img = models.URLField(max_length =200,blank=True,null=True)

ca_lens/forms.py
from django import forms

class ContactForm(forms.Form):
   name = forms.CharField(label='お名前', max_length=50)
   email = forms.EmailField(label='メールアドレス',)
   message = forms.CharField(label='メッセージ', widget=forms.Textarea)

ca_lens/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.db.models import Q
from .forms import ContactForm
from .models import Wantoitem, Main, Sub, Item_maker

from django.http import HttpResponse
from django.conf import settings
import textwrap
from django.core.mail import BadHeaderError, EmailMessage

# chrome関数
from . import def_chrome 
from urllib.parse import urlparse

def index(request):
    return render(request, 'ca_lens/index.html')
    
def preturn(request):
    return render(request, 'ca_lens/preturn.html')

def detail(request, slug):
    item = get_object_or_404(Wantoitem, slug=slug)
    main_lists = Main.objects.filter(wantoitem=item)
    sub_lists = Sub.objects.filter(wantoitem=item)
    return render(request, 'ca_lens/detail.html', {
        'item':item,
        'main_lists':main_lists,
        'sub_lists':sub_lists
        })

def maker_index(request):
    maker_list = Item_maker.objects.all()
    return render(request, 'ca_lens/maker_list.html', {
        'maker_list':maker_list
    })

def maker_detail(request, slug):
    maker = get_object_or_404(Item_maker, slug=slug)
    items = Wantoitem.objects.filter(maker_name=maker)
    return render(request, 'ca_lens/maker_detail.html', {
        'items':items,
        'maker':maker,
        })

def search_result(request):
    items = Wantoitem.objects.all().order_by('maker_name')
    maker_list = Item_maker.objects.all()
    query = request.GET.get('query')
    if query:
        items = items.filter(
        Q(item_name__icontains=query)|
        Q(maker_name__name__icontains=query)
        ).distinct()
        maker_lists = items.values_list('maker_name__name', flat=True)
        maker_list = maker_list.filter(name__in=maker_lists)
    return render(request, 'ca_lens/search_result.html', {
         'items':items,
         'maker_list':maker_list
        })

def delete(request): 
    if not request.user.is_superuser:
        return redirect('ca_lens:index')
    else:
        if request.method == 'POST':    
            item_pks = request.POST.getlist('delete') 
            Wantoitem.objects.filter(pk__in=item_pks).delete()
            return redirect('ca_lens:index')
        else:
            items = Wantoitem.objects.all()
            return render(request, 'ca_lens/delete.html', {'items':items})

def exclusion(request,slug):
    if not request.user.is_superuser:
        return redirect('ca_lens:detail', slug=slug)
    else:
        if request.method == 'POST':
            main_pks = request.POST.getlist('exclusion_main')
            exec_list_main = Main.objects.filter(pk__in=main_pks)
            for main in exec_list_main:
                domain_name = urlparse(main.main_url).netloc
                if 'www' in domain_name:
                    domain_name = domain_name.replace('www', '')
                with open('./ca_lens/pattern/except_sub_list.txt', mode='a') as f:
                    f.write('\n'+domain_name)
            exec_list_main.delete()

            sub_pks = request.POST.getlist('exclusion_sub')
            exec_list_sub = Sub.objects.filter(pk__in=sub_pks)
            for sub in exec_list_sub:
                domain_name = urlparse(sub.sub_url).netloc
                with open('./ca_lens/pattern/except_sub_list.txt', mode='a') as f:
                    f.write('\n'+domain_name)
            exec_list_sub.delete()
            return redirect('ca_lens:detail',slug=slug)
        else:
            item = get_object_or_404(Wantoitem, slug=slug)
            main_list = Main.objects.filter(wantoitem=item)
            sub_list = Sub.objects.filter(wantoitem=item)
            return render(request, 'ca_lens/exclusion.html', {
                'item':item, 
                'main_list':main_list,
                'sub_list':sub_list
                })

def contact(request):
  form = ContactForm(request.POST or None)
  if form.is_valid():
     name = form.cleaned_data['name']
     message = form.cleaned_data['message']
     email = form.cleaned_data['email']
     subject = 'お問い合わせありがとうございます。'
     contact = textwrap.dedent('''
        ※このメールはシステムからの自動返信です。

        {name} 様
        
        お問い合わせありがとうございます。
        以下の内容でお問い合わせを受け付けました。
        内容を確認させていただき、ご返信させていただきますので、少々お待ちください。

        ----------------------------------

        ・お名前
        {name}

        ・メールアドレス
        {email}

        ・メッセージ
        {message}
        
        -----------------------------------
        WEB: https://wanto-item.com/
     ''').format(
        name=name,
        email=email,
        message=message
     )
     to_list = [email]
     bcc_list = [settings.EMAIL_HOST_USER]
     try:
        message = EmailMessage(subject=subject, body=contact, to=to_list, bcc=bcc_list)
        message.send()
     except BadHeaderError:
        return HttpResponse('無効なヘッダが検出されました。')
     return redirect('ca_lens:done')

  return render(request, 'ca_lens/contact.html',{'form': form})

def done(request):
   return render(request, 'ca_lens/done.html')

ca_lens/templates/ca_lens/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <link rel='stylesheet' href="{% static 'ca_lens/css/style_base.css' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'ca_lens/icon/favicon_package/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'ca_lens/icon/favicon_package/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'ca_lens/icon/favicon_package/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'ca_lens/icon/favicon_package/site.webmanifest' %}">
    <link rel="mask-icon" href="{% static 'ca_lens/icon/favicon_package/safari-pinned-tab.svg' %}" color="#aeaeae">
    <meta name="msapplication-TileColor" content="#b8b8b8">
    <meta name="theme-color" content="#ffffff">
    <!-- <link rel="icon" href="{% static 'ca_lens/icon/favicon.ico' %}"> -->
    <script src="https://kit.fontawesome.com/81e08fdf06.js" crossorigin="anonymous"></script>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@400;700&family=Open+Sans:wght@400;700&display=swap" rel="stylesheet">
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-TM2RNP3WQR"></script>
    <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'G-TM2RNP3WQR');
    </script>
    {% block head %}
    {% endblock %}
</head>
<body>
    <header class="header">
        <div class="container">
            <div class="logo_header"><a href="{% url 'ca_lens:index' %}">WaNTo</a></div>
            <div class="maker_header"><a href="{% url 'ca_lens:maker_index' %}">メーカー</a></div>
            <form class="form_header" action="{% url 'ca_lens:search_result' %}" method="GET">
                    <input name="query" value="{{ request.GET.query }}" type="text" id="sbox" placeholder="検索"/>
                    <button type="submit" id="sbtn"><i class="fas fa-search"></i></button>
            </form>

        </div>
    </header>
    {% block content %}
    {% endblock %}
    <footer>
        <div class="container">
            <a href="{% url 'ca_lens:contact' %}" class="contact">CONTACT</a>    
            <a href="{% url 'ca_lens:preturn' %}" class="question">FAQ</a>
        </div>
    </footer>
</body>
</html>

ca_lens/templates/ca_lens/contact.html
{% extends 'ca_lens/base.html' %}
{% load static %}
{% block head %}
<link rel='stylesheet' href="{% static 'ca_lens/css/style_contact.css' %}">
{% endblock %}
{% block content %}
<main>
    <h1>お問い合わせ</h1>
    <form action="{% url 'ca_lens:contact' %}" method="POST" class="contact">
        {% csrf_token %}
        <input name="name" type="text" class="feedback-input" required="" placeholder="Name">   
        <input name="email" type="text" class="feedback-input" required="" placeholder="Email">
        <textarea name="message" class="feedback-input" required="" placeholder="Comment"></textarea>
        <input type="submit" value="SUBMIT">
    </form>
</main>
{% endblock %}

ca_lens/templates/ca_lens/delete.html
{% extends 'ca_lens/base.html' %}
{% load static %}
{% block head %}
<link rel='stylesheet' href="{% static 'ca_lens/css/style_other.css' %}">
{% endblock %}
{% block content %}
<main>

    <h3>削除</h3>
    <form action="{% url 'ca_lens:delete' %}" method="POST"　class="new_item">
        {% for item in items %}
        <p><input type="checkbox" name="delete" value="{{ item.pk }}"> {{ item.item_name }} </p>
        {% endfor %}
        {% csrf_token %}
        <button type="submit">削除</button>
    </form>
</main>
{% endblock %}

ca_lens/templates/ca_lens/detail.html
{% extends 'ca_lens/base.html' %}
{% load static %}
{% block head %}
<link rel='stylesheet' href="{% static 'ca_lens/css/style_detail.css' %}">
<title>{{ item.item_name }} みんなのレビュー・評価を一覧表示 - WaNTo(ワント)</title>
{% autoescape off %}
{{ item.meta_des }}
{% endautoescape %}
{% endblock %}
{% block content %}
<main>
    <div class="item_title">
        <div class="title_card"><a href="{% url 'ca_lens:maker_detail' item.maker_name.slug %}">{{ item.maker_name.name }}</a></div>
        <div class="title_card"><a>{{ item.item_name }}</a></div>
    </div>
    <div class="item_article_card">
        {% for main_list in main_lists %}
        <a href="{{ main_list.main_url }}" target="_blank">
            <div>{{ main_list.main_title }}</div>
            <img src="{{ main_list.main_ogp_img }}">
        </a>
        {% endfor %}
        {% for sub_list in sub_lists %}
        <a href="{{ sub_list.sub_url }}" target="_blank">
            <div>{{ sub_list.sub_title }}</div>
            <img src="{{ sub_list.sub_ogp_img }}">
        </a>
        {% endfor %}
    </div>
</main>
{% endblock %}

ca_lens/templates/ca_lens/done.html
{% extends 'ca_lens/base.html' %}
{% block content %}
<main>
    <h4 class="card-title">お問い合わせありがとうございます。</h4>
    <hr>
    <a href="{% url 'ca_lens:index' %}"><button type="button" class="btn btn-primary">トップページへ</button></a>
</main>
{% endblock%}

ca_lens/templates/ca_lens/exclusion.html
{% extends 'ca_lens/base.html' %}
{% load static %}
{% block head %}
<link rel='stylesheet' href="{% static 'ca_lens/css/style_other.css' %}">
{% endblock %}
{% block content %}
<main>
    <h3>除外</h3>
    <form action="{% url 'ca_lens:exclusion' item.slug %}" method="POST" 　class="new_item">
        {% for main in main_list %}
        <p><input type="checkbox" name="exclusion_main" value="{{ main.pk }}"> {{ main.main_title }} </p>
        {% endfor %}
        {% for sub in sub_list %}
        <p><input type="checkbox" name="exclusion_sub" value="{{ sub.pk }}"> {{ sub.sub_title }} </p>
        {% endfor %}

        {% csrf_token %}
        <button type="submit">除外</button>
    </form>
</main>
{% endblock %}

ca_lens/templates/ca_lens/index.html
{% extends 'ca_lens/base.html' %}
{% load static %}
{% block head %}
<link rel='stylesheet' href="{% static 'ca_lens/css/style_index.css' %}">
<title>カメラレンズ トップページ - WaNTo(ワント)</title>
<meta name="description" content="カメラレンズのレビューや評価サイトだけを表示したいというお悩みはありませんか？本サイトでは、カメラレンズのレビューや評価サイトサイトだけを一覧表示！あなたに最適なアイテムを見つけてください。">
{% endblock %}
{% block content %}
<main>
    <div class="main_pic">
        <img src="{% static 'ca_lens/img/main_pic.jpg' %}">
        <p class="main_title">レンズ</p>
        <p class="sub_title">みんなのレビューから<br>あなたに最適なアイテムを</p>
    </div>
    <div class="navi_grid">
        <div>
            <p class="large">操作は簡単！</p>
            <p class="normal">メーカーをクリック</p>
            <p class="small">（<a href="{% url 'ca_lens:maker_index' %}">こちら</a>からも移動できます）</p>
            <img class="sp" src="{% static 'ca_lens/img/sp_1.png' %}">
            <img class="pc" src="{% static 'ca_lens/img/pc_1.png' %}">
        </div>
        <div>
            <p class="normal">お好きなメーカーを<br>クリック</p>
            <img class="sp" src="{% static 'ca_lens/img/sp_2.png' %}">
            <img class="pc" src="{% static 'ca_lens/img/pc_2.png' %}">
        </div>
        <div>
            <p class="normal">気になるアイテムを<br>クリック</p>
            <img class="sp" src="{% static 'ca_lens/img/sp_3.png' %}">
            <img class="pc" src="{% static 'ca_lens/img/pc_3.png' %}">
        </div>
        <div>
            <p class="normal">みんなの商品レビュー<br>を一覧表示</p>
            <img class="sp" src="{% static 'ca_lens/img/sp_4.png' %}">
            <img class="pc" src="{% static 'ca_lens/img/pc_4.png' %}">
        </div>
    </div>
</main>
{% endblock %}

ca_lens/templates/ca_lens/maker_detail.html
{% extends 'ca_lens/base.html' %}
{% load static %}
{% block head %}
<link rel='stylesheet' href="{% static 'ca_lens/css/style_list.css' %}">
<title>{{ maker.name }}レンズ みんなのレビュー・評価を一覧表示 - WaNTo(ワント)</title>
{% autoescape off %}
{{ maker.meta_des }}
{% endautoescape %}
{% endblock %}
{% block content %}
<main>
    {% if items %}
    <div class="item_title">
        <div class="title_card"><a href="{% url 'ca_lens:maker_detail' maker.slug %}">{{ maker.name }}</a></div>
        <div class="item_card">
            {% for item in items %}
            <div class="item"><a href="{% url 'ca_lens:detail' item.slug %}">{{ item.item_name }}</a></div>
            {% endfor %}
        </div>
    </div>
    {% else %}
    <div class="item_title">
        <div class="title_card"><a href="{% url 'ca_lens:maker_detail' maker.slug %}">{{ maker.name }}</a></div>
        <h3>準備中</h3>
    {% endif %}
</main>
{% endblock %}

ca_lens/templates/ca_lens/maker_list.html
{% extends 'ca_lens/base.html' %}
{% load static %}
{% block head %}
<link rel='stylesheet' href="{% static 'ca_lens/css/style_list.css' %}">
<title>カメラレンズ メーカー一覧 - WaNTo(ワント)</title>
<meta name="description" content="カメラレンズのレビューや評価サイトだけを表示したいというお悩みはありませんか？本サイトでは、カメラレンズのレビューや評価サイトサイトだけを一覧表示！あなたに最適なアイテムを見つけてください。">
{% endblock %}
{% block content %}
<main>
    {% for maker in maker_list %}
    <div class="item_title">
        <div class="title_card"><a href="{% url 'ca_lens:maker_detail' maker.slug %}">{{ maker.name }}</a></div>
    </div>
    {% endfor %}
</main>
{% endblock %}

ca_lens/templates/ca_lens/preturn.html
{% extends 'ca_lens/base.html' %}
{% load static %}
{% block content %}
<main>
<h1>準備中</h1>
<a href="{% url 'ca_lens:index' %}"><button type="button" class="btn btn-primary">トップページへ</button></a>
</main>
{% endblock %}

ca_lens/templates/ca_lens/search_result.html
{% extends 'ca_lens/base.html' %}
{% load static %}
{% block head %}
<link rel='stylesheet' href="{% static 'ca_lens/css/style_list.css' %}">
{% endblock %}
{% block content %}
<main>
    {% if items %}
    {% for maker in maker_list %}
    <div class="item_title">
        <div class="title_card"><a href="{% url 'ca_lens:maker_detail' maker.slug %}">{{ maker.name }}</a></div>
        <div class="item_card">
            {% for item in items %}
            {% if item.maker_name == maker %}
            <div class="item"><a href="{% url 'ca_lens:detail' item.slug %}">{{ item.item_name }}</a></div>
            {% endif %}
            {% endfor %}
        </div>
    </div>
    {% endfor %}
    {% else %}
    <h1>検索結果なし</h1>
    {% endif %}
</main>
{% endblock %}