app/urls.py
from django.urls import path

from . import views

app_name = 'app'
urlpatterns = [
    path('rayout',views.rayout,name='rayout'),
    path('',  views.index, name='index'),
    path('item/<slug:slug>', views.detail, name='detail'),
    path('form', views.form, name='form'),
    path('delete', views.delete, name='delete'),
    path('reload',views.reload, name='reload'),
    path('item/<slug:slug>/edit', views.edit,name='edit'),
    path('item/<slug:slug>/exclusion', views.exclusion, name='exclusion'),
    path('maker_index',views.maker_index, name='maker_index'),
    path('maker/<slug:slug>', views.maker_detail, name='maker_detail'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', admin.site.urls),
]

app/templates/app/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel='stylesheet' href="{% static 'app/css/style_base.css' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'app/icon/favicon_package/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'app/icon/favicon_package/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'app/icon/favicon_package/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'app/icon/favicon_package/site.webmanifest' %}">
    <link rel="mask-icon" href="{% static 'app/icon/favicon_package/safari-pinned-tab.svg' %}" color="#aeaeae">
    <meta name="msapplication-TileColor" content="#b8b8b8">
    <meta name="theme-color" content="#ffffff">
    <!-- <link rel="icon" href="{% static 'app/icon/favicon.ico' %}"> -->
    <script src="https://kit.fontawesome.com/81e08fdf06.js" crossorigin="anonymous"></script>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@400;700&family=Open+Sans:wght@400;700&display=swap" rel="stylesheet">
    <title>WaNTo</title>
    {% block head %}
    {% endblock %}
</head>
<body>
    <header class="header">
        <div class="container">
            <div class="logo_header"><a href="{% url 'app:index' %}">WaNTo</a></div>
            <div class="maker_header"><a href="{% url 'app:maker_index' %}">メーカー</a></div>
            <form class="form_header" action="{% url 'app:index' %}" method="GET">
                    <input name="query" value="{{ request.GET.query }}" type="text" id="sbox" placeholder="検索"/>
                    <button type="submit" id="sbtn"><i class="fas fa-search"></i></button>
            </form>

        </div>
    </header>
    {% block content %}
    {% endblock %}
    
</body>
</html>

app/templates/app/delete.html
{% extends 'app/base.html' %}
{% load static %}
{% block head %}
<link rel='stylesheet' href="{% static 'app/css/style_other.css' %}">
{% endblock %}
{% block content %}
<main>

    <h3>削除</h3>
    <form action="{% url 'app:delete' %}" method="POST"　class="new_item">
        {% for item in items %}
        <p><input type="checkbox" name="delete" value="{{ item.pk }}"> {{ item.item_name }} </p>
        {% endfor %}
        {% csrf_token %}
        <button type="submit">削除</button>
    </form>
</main>
{% endblock %}

app/templates/app/detail.html
{% extends 'app/base.html' %}
{% load static %}
{% block head %}
<link rel='stylesheet' href="{% static 'app/css/style_detail.css' %}">
{% endblock %}
{% block content %}
<main>
    <div class="item_maker">
        <div class="maker_card"><a href="{% url 'app:maker_detail' item.maker_name.slug %}">{{ item.maker_name.name }}</a></div>
        <div class="maker_card">{{ item.item_name }}</div>
        <div class="item_card">
            {% for main_list in main_lists %}
            <a href="{{ main_list.main_url }}" target="_blank" >
                <div>{{ main_list.main_title }}</div>
                <img src="{{ main_list.main_ogp_img }}">
            </a>
            {% endfor %}
            {% for sub_list in sub_lists %}
            <a href="{{ sub_list.sub_url }}" target="_blank" >
                <div>{{ sub_list.sub_title }}</div>
                <img src="{{ sub_list.sub_ogp_img }}">
            </a>
            {% endfor %}
        </div>
    </div>
</main>
{% endblock %}

app/templates/app/exclusion.html
{% extends 'app/base.html' %}
{% load static %}
{% block head %}
<link rel='stylesheet' href="{% static 'app/css/style_other.css' %}">
{% endblock %}
{% block content %}
<main>
    <h3>除外</h3>
    <form action="{% url 'app:exclusion' item.slug %}" method="POST" 　class="new_item">
        {% for main in main_list %}
        <p><input type="checkbox" name="exclusion_main" value="{{ main.pk }}"> {{ main.main_title }} </p>
        {% endfor %}
        {% for sub in sub_list %}
        <p><input type="checkbox" name="exclusion_sub" value="{{ sub.pk }}"> {{ sub.sub_title }} </p>
        {% endfor %}

        {% csrf_token %}
        <button type="submit">除外</button>
    </form>
</main>
{% endblock %}

app/templates/app/form.html
{% extends 'app/base.html' %}
{% load static %}
{% block head %}
<link rel='stylesheet' href="{% static 'app/css/style_other.css' %}">
{% endblock %}
{% block content %}
<main>
    <h3>アイテム</h3>
    <form method="POST" class='new_item'>
        {% csrf_token %}
        {{ form }}
        <button type="submit">登録</button> 
    </form>
</main>
{% endblock %}

app/templates/app/index.html
{% extends 'app/base.html' %}
{% load static %}
{% block head %}
<link rel='stylesheet' href="{% static 'app/css/style_index.css' %}">
{% endblock %}
{% block content %}
<main>
    {% if items %}
    {% for maker in maker_list %}
    <div class="item_maker">
        <div class="maker_card"><a href="{% url 'app:maker_detail' maker.slug %}">{{ maker.name }}</a></div>
        <div class="item_card">
            {% for item in items %}
            {% if item.maker_name == maker %}
            <div class="item"><a href="{% url 'app:detail' item.slug %}">{{ item.item_name }}</a></div>
            {% endif %}
            {% endfor %}
        </div>
    </div>
    {% endfor %}
    {% endif %}
</main>
{% endblock %}

app/templates/app/rayout_detail.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8" />
    <title>Document</title>
    <link rel='stylesheet' href="{% static 'app/css/style_base.css' %}">
    <link rel='stylesheet' href="{% static 'app/css/style_detail.css' %}">
</head>

<body>
    <header class="header">
        <div class="container">
            <div class="logo_header">WaNTo</div>
            <div class="maker_header">メーカー</div>
            <div class="tag_header">タグ</div>
            <form class="form_header" action="">
                <div class="wrap_input">
                    <input type="search">
                </div>
            </form>

        </div>
    </header>
    <main>
        <div class="item_maker">
            <div class="maker_card">メーカー</div>
            <div class="maker_card">アイテム</div>
            <div class="item_card">
                <div><img src="https://pc.watch.impress.co.jp/img/pcw/list/1290/745/H00.jpg">URL1</div>
                <div>URL2</div>
                <div>URL3</div>
                <div>URL4</div>
            </div>
        </div>
        <div class="item_maker">
            <div class="maker_card">メーカー</div>
            <div class="maker_card">アイテム</div>
            <div class="item_card">
                <div><img src="https://pc.watch.impress.co.jp/img/pcw/list/1290/745/H00.jpg">URL1</div>
                <div>URL2</div>
                <div>URL3</div>
                <div>URL4</div>
            </div>
        </div>
    </main>
</body>

</html>

app/templates/app/rayout_index.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8" />
    <title>Document</title>
    <link rel='stylesheet' href="{% static 'app/css/style_base.css' %}">
    <link rel='stylesheet' href="{% static 'app/css/style_index.css' %}">
</head>

<body>
    <header class="header">
        <div class="container">
            <div class="logo_header">WaNTo</div>
            <div class="maker_header">メーカー</div>
            <div class="tag_header">タグ</div>
            <form class="form_header" action="">
                <div class="wrap_input">
                    <input type="search">
                </div>
            </form>

        </div>
    </header>
    <main>
        <div class="item_maker">
            <div class="maker_card">メーカー1</div>
            <!-- <div class="item_card">
                <div>アイテム1</div>
                <div>アイテム2</div>
                <div>アイテム3</div>
                <div>アイテム4</div>
            </div> -->
        </div>
        <div class="item_maker">
            <div class="maker_card">メーカー2</div>
            <!-- <div class="item_card">
                <div>アイテム5</div>
                <div>アイテム6</div>
                <div>アイテム7</div>
                <div>アイテム8</div>
                <div>アイテム9</div>
            </div> -->
        </div>
    </main>
</body>

</html>

app/templates/app/reload.html
{% extends 'app/base.html' %}
{% load static %}
{% block head %}
<link rel='stylesheet' href="{% static 'app/css/style_other.css' %}">
{% endblock %}
{% block content %}
<main>
    <h3>更新</h3>
    <form action="{% url 'app:reload' %}" method="POST"　class="new_item">
        {% for item in items %}
        <p><input type="checkbox" name="reload" value="{{ item.pk }}"> {{ item.item_name }} </p>
        {% endfor %}
        {% csrf_token %}
        <button type="submit">更新</button>
    </form>
</main>
{% endblock %}